// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StrasseWebsite.Data;

#nullable disable

namespace StrasseWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604114359_AdicionarImovelEPessoa")]
    partial class AdicionarImovelEPessoa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StrasseWebsite.Models.ImagemImovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImovelId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId");

                    b.ToTable("ImagensImoveis");
                });

            modelBuilder.Entity("StrasseWebsite.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CidadeEstado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoImovel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConstrutoraResponsavel")
                        .HasColumnType("text");

                    b.Property<int>("CorretorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagamentoDisponivel")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProprietarioId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeBanheiros")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeQuartos")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeSalas")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeVagasGaragem")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TamanhoConstruido")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TamanhoTerreno")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("TemAcademia")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemGaragem")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemPiscina")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Transacao")
                        .HasColumnType("integer");

                    b.Property<string>("UrlImagemPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorretorId");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("StrasseWebsite.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("StrasseWebsite.Models.ImagemImovel", b =>
                {
                    b.HasOne("StrasseWebsite.Models.Imovel", null)
                        .WithMany("GaleriaImagens")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StrasseWebsite.Models.Imovel", b =>
                {
                    b.HasOne("StrasseWebsite.Models.Pessoa", "Corretor")
                        .WithMany("ImoveisComoCorretor")
                        .HasForeignKey("CorretorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StrasseWebsite.Models.Pessoa", "Proprietario")
                        .WithMany("ImoveisComoProprietario")
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Corretor");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("StrasseWebsite.Models.Imovel", b =>
                {
                    b.Navigation("GaleriaImagens");
                });

            modelBuilder.Entity("StrasseWebsite.Models.Pessoa", b =>
                {
                    b.Navigation("ImoveisComoCorretor");

                    b.Navigation("ImoveisComoProprietario");
                });
#pragma warning restore 612, 618
        }
    }
}
